### ISSUE TITLE
后退后再进入之前的图片还存在

### ISSUE THREAD

**Issue by chen-can** [smalltee/robby-image-upload#2]
我把组件放到APP的一个页面里，当我选完照片后，照片会显示在页面上，但我退出这个页面后再进来后，那个图片还在组件上显示，除非我退出APP重新进来才会消失。  删除图片时在进入还说有图片

**Comment by smalltee** [comment]
参考一下组件6月6日的评论，“434545299@qq.com”的评论。
https://ext.dcloud.net.cn/plugin?id=326#rating

**Comment by chen-can** [comment]
我试了下基础库2.7.0 会有问题 回退到2.4.3又正常了 太坑了

**Comment by chen-can** [comment]
不好意思在真机上查看还是存在相同的问题

**Comment by chen-can** [comment]
作者可以参考下http://varyu.com/notes/521.html 我自己最后使用了这条链接解决了我的问题，希望作者有空改善下组件 谢谢

**Comment by smalltee** [comment]
好的，谢谢

**Comment by alterhu2020** [comment]
@chen-can 没太明白你说的链接中的解决方法，你意思是采用canvas 进行绘制吗？
@smalltee  这个问题太严重了，有没有什么解决方法。。。。换了小程序开发工具中的2.7.1但是只能在开发工具里面有用，换成了真实手机上，还是会有这个问题。

另外使用了destory()生命周期函数不管在父组件还是子组件中都没有效果。

测试的环境是:
小程序开发者工具库中，基础库：2.7.5

**Comment by smalltee** [comment]
已改。
参考这位的评论602044025@qq.com         2019-07-19

已经找到解决方法了，前面那些人提的，用destroyed来清空数据完全没用，要是多张图片，根本没有多大效果，必须多次进入多次退出才会全部消失掉。这种方法不可取。

其实很简单，在修改这个组件，在data里面新增一个变量imageItems(随便命名的，不要介意)，然后在组件里onload方法里将value赋值给imageItems就行了，然后全局有用到value的地方全部替换成imageItems，这样子就可以解决组件使用后添加多张图片导致界面销毁后数据还有留存的问题。

**Comment by LinChengChun** [comment]
楼主，我发现当前的版本仍然有这个问题，我是这样解决的，由于页面和组件都各自维护图片，因此value属性只在非编辑状态有效。 
mounted: function() {
         if (!this.enableEdit) // 解决选择图片，二次进入页面图片有缓存问题
              this.imageList = this.value
}
